apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrape-service
  namespace: leadfactory-pipeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scrape-service
  template:
    metadata:
      labels:
        app: scrape-service
    spec:
      containers:
      - name: scrape-service
        image: leadfactory/scrape-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: SERVICE_NAME
          value: "scrape"
        - name: SERVICE_PORT
          value: "8001"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: scrape-service
  namespace: leadfactory-pipeline
spec:
  selector:
    app: scrape-service
  ports:
  - port: 8001
    targetPort: 8001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrich-service
  namespace: leadfactory-pipeline
spec:
  replicas: 5
  selector:
    matchLabels:
      app: enrich-service
  template:
    metadata:
      labels:
        app: enrich-service
    spec:
      containers:
      - name: enrich-service
        image: leadfactory/enrich-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: SERVICE_NAME
          value: "enrich"
        - name: SERVICE_PORT
          value: "8002"
        - name: REDIS_URL
          value: "redis://redis:6379/1"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: enrich-service
  namespace: leadfactory-pipeline
spec:
  selector:
    app: enrich-service
  ports:
  - port: 8002
    targetPort: 8002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dedupe-service
  namespace: leadfactory-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dedupe-service
  template:
    metadata:
      labels:
        app: dedupe-service
    spec:
      containers:
      - name: dedupe-service
        image: leadfactory/dedupe-service:latest
        ports:
        - containerPort: 8003
        env:
        - name: SERVICE_NAME
          value: "dedupe"
        - name: SERVICE_PORT
          value: "8003"
        - name: REDIS_URL
          value: "redis://redis:6379/2"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: dedupe-service
  namespace: leadfactory-pipeline
spec:
  selector:
    app: dedupe-service
  ports:
  - port: 8003
    targetPort: 8003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: score-service
  namespace: leadfactory-pipeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: score-service
  template:
    metadata:
      labels:
        app: score-service
    spec:
      containers:
      - name: score-service
        image: leadfactory/score-service:latest
        ports:
        - containerPort: 8004
        env:
        - name: SERVICE_NAME
          value: "score"
        - name: SERVICE_PORT
          value: "8004"
        - name: REDIS_URL
          value: "redis://redis:6379/3"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: score-service
  namespace: leadfactory-pipeline
spec:
  selector:
    app: score-service
  ports:
  - port: 8004
    targetPort: 8004

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockup-service
  namespace: leadfactory-pipeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mockup-service
  template:
    metadata:
      labels:
        app: mockup-service
    spec:
      containers:
      - name: mockup-service
        image: leadfactory/mockup-service:latest
        ports:
        - containerPort: 8005
        env:
        - name: SERVICE_NAME
          value: "mockup"
        - name: SERVICE_PORT
          value: "8005"
        - name: REDIS_URL
          value: "redis://redis:6379/4"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: mockup-service
  namespace: leadfactory-pipeline
spec:
  selector:
    app: mockup-service
  ports:
  - port: 8005
    targetPort: 8005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: leadfactory-pipeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: leadfactory/email-service:latest
        ports:
        - containerPort: 8006
        env:
        - name: SERVICE_NAME
          value: "email"
        - name: SERVICE_PORT
          value: "8006"
        - name: REDIS_URL
          value: "redis://redis:6379/5"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: leadfactory-pipeline
spec:
  selector:
    app: email-service
  ports:
  - port: 8006
    targetPort: 8006

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: leadfactory-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: leadfactory/orchestrator:latest
        ports:
        - containerPort: 8000
        env:
        - name: SERVICE_NAME
          value: "orchestrator"
        - name: SERVICE_PORT
          value: "8000"
        - name: REDIS_URL
          value: "redis://redis:6379/6"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: leadfactory-pipeline
spec:
  selector:
    app: orchestrator
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer