version: '3.8'

services:
  metrics-exporter:
    build:
      context: ..
      dockerfile: docker/metrics/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
      - ENVIRONMENT=development
      - DAILY_BUDGET=50.0
      - MONTHLY_BUDGET=1000.0
      - DB_PATH=/data/lead_factory.db
    volumes:
      - ../db:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Example Prometheus service (optional)
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - metrics-exporter
    restart: unless-stopped

  # Example Grafana service (optional)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
