[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "C4", "T20", "SIM", "PTH", "Q"]
# Ignore rules that may cause issues with Python 3.9 compatibility
ignore = ["F722", "F821", "E501", "F401"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["F811", "S101"]
"**/__init__.py" = ["F401"]
"bin/enrich.py" = ["S608", "F401"]
"bin/dedupe.py" = ["S608", "F401"]
