[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "C4", "T20", "SIM", "PTH", "Q"]
# Ignore rules that may cause issues with Python 3.9 compatibility
ignore = ["F722", "F821", "E501", "F401"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["F811", "S101"]
"**/__init__.py" = ["F401"]
"bin/enrich.py" = ["S608", "F401"]
"bin/dedupe.py" = ["S608", "F401"]

[tool.bandit]
# Bandit configuration to exclude common false positives
# and focus on real security issues for LeadFactory

# Skip tests that frequently generate false positives in this codebase
# B106: Hardcoded password detection (many false positives in test/config files)
# B324: Weak hash algorithms (MD5/SHA1 often used for non-security purposes like sharding)
# B608: SQL injection detection for parameterized queries (our SQL uses proper parameterization)
# B404: Subprocess import (CLI commands legitimately use subprocess)
# B603: Subprocess without shell (safe subprocess calls in CLI)
# B110: Try/except pass (acceptable pattern in some error handling scenarios)
# B105: Hardcoded password string (false positives on constant event names)
# B107: Hardcoded password default (false positives on parameter names)
skips = ["B106", "B324", "B608", "B404", "B603", "B110", "B105", "B107"]

# Exclude directories and patterns
exclude_dirs = [
    "tests",
    "venv",
    ".venv",
    "env",
    ".env",
    ".git",
    ".github",
    ".mypy_cache",
    ".pytest_cache",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    "tasks",
    ".ruff_cache",
    "bin",
    "scripts",
    "archive",
    "backup_files",
    "dedupe_backups"
]
