apiVersion: v1
kind: ConfigMap
metadata:
  name: leadfactory-config
  namespace: leadfactory
data:
  # Database configuration
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "leadfactory"

  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  # Kafka configuration
  KAFKA_BROKERS: "kafka-service:9092"

  # Service configuration
  PYTHONPATH: "/app"
  PYTHONUNBUFFERED: "1"

  # Performance settings
  WORKER_PROCESSES: "2"
  MAX_CONCURRENT_REQUESTS: "100"

  # Monitoring
  PROMETHEUS_PORT: "9090"
  JAEGER_ENDPOINT: "http://jaeger-service:14268/api/traces"
