apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockup-service
  namespace: leadfactory
  labels:
    app: mockup-service
    component: pipeline
spec:
  replicas: 3  # Always maintain 3 replicas as per requirement
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mockup-service
  template:
    metadata:
      labels:
        app: mockup-service
    spec:
      # GPU node selector for Hetzner GPU instances
      nodeSelector:
        accelerator: nvidia-tesla-v100
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: mockup
        image: leadfactory/mockup:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
        env:
        - name: SERVICE_NAME
          value: "mockup-service"
        - name: WORKER_TYPE
          value: "mockup"
        - name: DISPLAY
          value: ":99"
        - name: CHROMIUM_PATH
          value: "/usr/bin/chromium"
        - name: GPU_ENABLED
          value: "true"
        envFrom:
        - configMapRef:
            name: leadfactory-config
        - secretRef:
            name: leadfactory-secrets
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: mockup-service
  namespace: leadfactory
spec:
  selector:
    app: mockup-service
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP
---
# Custom HPA for queue-based scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mockup-hpa
  namespace: leadfactory
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mockup-service
  minReplicas: 3  # Always maintain 3 replicas
  maxReplicas: 15  # Scale up when queue > 2k
  metrics:
  - type: External
    external:
      metric:
        name: kafka_consumer_lag
        selector:
          matchLabels:
            topic: "mockups.requested"
      target:
        type: Value
        value: "2000"  # Scale when queue exceeds 2k
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
