global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'lead-factory-metrics'
    static_configs:
      - targets: ['metrics-exporter:8000']
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
