name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install -r requirements.txt; fi

      - name: Log versions
        run: |
          echo "\n=== Python Environment Info ===\n"
          python --version
          echo "\n=== Python Package Versions ===\n"
          pip list
          echo "\n=== Tool Versions ===\n"
          python -c "import black; print(f'Black: {black.__version__}')"
          python -c "import ruff; print(f'Ruff: {ruff.__version__}')"
          python -c "import pytest; print(f'Pytest: {pytest.__version__}')"
          python -c "import mypy; print(f'MyPy: {mypy.__version__}')"
          python -c "import bandit; print(f'Bandit: {bandit.__version__}')"
          echo "\n=== System Info ===\n"
          uname -a
          echo "\n=============================\n"

      - name: Lint with Black
        run: |
          black --check .

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Security scan with Bandit
        run: |
          bandit -r . -o bandit-report.txt -f txt

      - name: Test with pytest
        run: |
          pytest --cov=leadfactory --cov-report=xml --cov-fail-under=80

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            bandit-report.txt
            .coverage
