name: Format Code

on:
  pull_request:
    branches: [ main, master, feature/* ]
  push:
    branches: [ main, master, feature/* ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==24.4.2
      - name: Format code
        run: |
          python scripts/ci_format.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-format code with Black"
          git push
