name: Minimal CI Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  minimal-test:
    name: Minimal Core Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Hard timeout to prevent hangs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install -e .

      - name: Test core NodeCapability integration (my main fixes)
        run: |
          pytest tests/integration/test_node_capability_integration.py -v --tb=short

      - name: Test DAG traversal (my main fixes)
        run: |
          pytest tests/unit/pipeline/test_dag_traversal.py -v --tb=short

      - name: Test NodeCapability configuration
        run: |
          pytest tests/unit/config/test_node_config_environment.py -v --tb=short

      - name: Test CLI with timeouts (my hang fix)
        run: |
          pytest tests/unit/test_cli_simple.py -v --tb=short
