name: Pytest Minimal CI

on:
  push:
    branches: [ fix-ci-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  pytest-test:
    name: Pytest Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      
      - name: Run simple test
        run: |
          mkdir -p tests/minimal
          echo 'def test_minimal(): assert True' > tests/minimal/test_minimal.py
          python -m pytest tests/minimal/test_minimal.py -v
