name: Anthrasite Lead-Factory Minimal CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  minimal-check:
    name: Minimal Check
    runs-on: ubuntu-lates
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simple verification
        run: |
          echo "Minimal CI workflow is running"
          echo "Repository successfully checked out"
          ls -la

      - name: Report success
        run: |
          echo "Minimal check completed successfully"
          echo "CI pipeline is verified to be functional"
